// General
export const INCREMENT_REQUEST = 'INCREMENT_REQUEST'
export const DECREMENT_REQUEST = 'DECREMENT_REQUEST'

// Robin API
export const LOCATIONS_REQUESTED = 'LOCATIONS_REQUESTED'
export const LOCATIONS_SUCCESS = 'LOCATIONS_SUCCESS'
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR'
export const SPACES_REQUESTED = 'SPACES_REQUESTED'
export const SPACES_SUCCESS = 'SPACES_SUCCESS'
export const SPACES_ERROR = 'SPACES_ERROR'
export const SPACE_REQUESTED = 'SPACE_REQUESTED'
export const SPACE_SUCCESS = 'SPACE_SUCCESS'
export const SPACE_ERROR = 'SPACE_ERROR'
export const SPACE_RESET = 'SPACE_RESET'
